//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlasServiceCenter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AtlasServiceCenterEntities : DbContext
    {
        public AtlasServiceCenterEntities()
            : base("name=AtlasServiceCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bonuses> Bonuses { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Devices> Devices { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<OrderStatuses> OrderStatuses { get; set; }
        public virtual DbSet<Parts> Parts { get; set; }
        public virtual DbSet<Penalties> Penalties { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<RepairOrderParts> RepairOrderParts { get; set; }
        public virtual DbSet<RepairOrders> RepairOrders { get; set; }
        public virtual DbSet<RepairOrderWorks> RepairOrderWorks { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SalaryPayments> SalaryPayments { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
