//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlasServiceCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonuses
    {
        public int BonusId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime BonusDate { get; set; }
        public decimal Amount { get; set; }
        public string Reason { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
