//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlasServiceCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryPayments
    {
        public int SalaryPaymentId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime PeriodStart { get; set; }
        public System.DateTime PeriodEnd { get; set; }
        public decimal BaseSalary { get; set; }
        public decimal BonusesTotal { get; set; }
        public decimal PenaltiesTotal { get; set; }
        public decimal FinalAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string Comment { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
